name: Build Aseprite WASM

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.39
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Instalamos dependencias necesarias que a veces el contenedor de emsdk no trae
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zip unzip curl

      - name: Make build script executable
        run: chmod +x web_trial/build.sh

      - name: Run build script
        env:
          ROOT_DIR: ${{ github.workspace }}
        run: |
          set -e # Esto hace que el Action se detenga si un comando falla
          cd web_trial
          ./build.sh
          
      - name: Upload built bundle
        if: success() # Solo sube si todo salió bien
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-web-trial-built
          path: web_trial/aseprite-web-trial.zip
